name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'proj3/SE_G25-main/proj2/frontend/**'
  pull_request:
    # paths:
    #   - 'proj3/SE_G25-main/proj2/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./proj3/SE_G25-main/proj2/frontend

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: proj3/SE_G25-main/proj2/frontend/package-lock.json

    - run: npm ci

    # Checks if the app compiles correctly
    - run: npm run build